config/routes.rb
Agetop::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "posts/index"

  get "posts/show"

  get "spots/index"

  get "equipments/reviews"
  get "site/defesa_previa"
  get "site/recurso"
  get "site/print_defesa_previa"
  post "site/print_defesa_previa"
  post "site/print_recurso"

  resources :pages, :posts
  resources :spots
  
  devise_for :users
  

  root :to => "site#index"
end

app/models/block.rb
class Block < ActiveRecord::Base
  has_many :links
end

app/models/defesa.rb
class Defesa
  include ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  
  attr_accessor :nome, :proprietario_condutor, :placa, :cor, :marca_modelo, :ano, :numero_auto, :data_auto, :horario_auto, :artigo_auto, :rodovia_auto, :km_auto, :municipio_auto, :residente, :bairro, :cidade, :cep, :fone, :uf, :identidade, :cpf, :cnh, :uf_cnh, :razoes
                
  validates_presence_of :nome, :proprietario_condutor, :placa, :cor, :marca_modelo, :ano, :numero_auto, :data_auto, :horario_auto, :artigo_auto, :rodovia_auto, :km_auto, :municipio_auto, :residente, :bairro, :cidade, :cep, :fone, :uf, :identidade, :cpf, :cnh, :uf_cnh, :razoes
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  has_many :reviews
  
  paginates_per 25
  
  validates_presence_of :name
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :block
  belongs_to :page
  belongs_to :post
  has_attached_file :image
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :page
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 25
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/recurso.rb
class Recurso
  include ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  
  attr_accessor :nome, :proprietario_condutor, :placa, :cor, :marca_modelo, :ano, :chassi_renavam, :numero_auto, :data_auto, :horario_auto, :artigo_auto, :rodovia_auto, :km_auto, :municipio_auto, :residente, :bairro, :cidade, :cep, :fone, :uf, :identidade, :cpf, :cnh, :uf_cnh, :razoes, :empresa, :cancelamento_restituicao, :banco, :agencia, :conta_corrente
                
  validates_presence_of :nome, :proprietario_condutor, :placa, :cor, :marca_modelo, :ano, :chassi_renavam, :numero_auto, :data_auto, :horario_auto, :artigo_auto, :rodovia_auto, :km_auto, :municipio_auto, :residente, :bairro, :cidade, :cep, :fone, :uf, :identidade, :cpf, :cnh, :uf_cnh, :razoes, :empresa, :cancelamento_restituicao, :banco, :agencia, :conta_corrente
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :equipment
  has_attached_file :pdf, :url => '/system/:class/:attachment/:id/:style/:filename'
  
  validates_presence_of :equipment, :pdf
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  has_attached_file :pdf, :url => '/system/:class/:attachment/:id/:style/:filename'
  
  paginates_per 25
  
  validates_presence_of :pdf
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource

  before_filter :load_defaults

  protected

  def layout_by_resource
    if devise_controller?
      "signin"
    else
      "application"
    end
  end
  
  def load_defaults
    @menu = Block.where(:name => "Menu").first.links.all
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController

  def reviews
    @equips = Equipment.joins(:reviews).order(:name).page params[:page]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('created_at DESC').page params[:page]
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").limit(5)
  end
  
  def defesa_previa
    @defesa = Defesa.new
  end
  
  def print_defesa_previa
    @defesa = Defesa.new(params[:defesa])
    if !@defesa.valid?
      flash.now[:warning] = 'TODOS os campos devem ser preenchidos.'
      render 'defesa_previa'
      return
    end
    
    render :layout => false
    render :pdf => "print_defesa_previa"
  end
  
  def recurso
    @recurso = Recurso.new
  end
  
  def print_recurso
    @recurso = Recurso.new(params[:recurso])
    if !@recurso.valid?
      flash.now[:warning] = 'TODOS os campos devem ser preenchidos.'
      render 'recurso'
      return
    end
    
    render :layout => false
    render :pdf => "print_recurso"
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    @spots = Spot.order('created_at DESC').page params[:page]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def get_link(link)
    if link.page.present?
      return link_to link.title, link.page
    end
    
    if link.post.present?
      return link_to link.title, link.post
    end
    
    return link_to link.title, link.url
  end
  
  def data_formatada(d)
    return d.strftime("%d/%m/%Y")
  end
  
  def hora_formatada(d)
    return d.strftime("%H:%M")
  end
  
  def wicked_pdf_stylesheet_link_tag(*sources)
      css_dir = "#{Rails.root.join('app', 'assets', 'stylesheets')}/"
      sources.collect { |source|
        new_path = css_dir + source
        "<style type='text/css'>#{File.read(new_path)}</style>"
      }.join("\n").html_safe
    end

    def wicked_pdf_image_tag(img, options={})
      image_tag "file://#{Rails.root.join('public')}#{img}", options
    end

    def wicked_pdf_javascript(jsfile, options={})
      javascript_src_tag "file://#{Rails.root.join('public')}#{jsfile}", options
    end

    def wicked_pdf_javascript_include_tag(*sources)
      sources.collect{ |source| wicked_pdf_javascript_src_tag(source, {}) }.join("\n").html_safe
    end

end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/site/defesa_previa.html.erb
<div class="grid_12">
	<div class="inner">
		<h1>Formulário para Defesa Prévia</h1>

		<% flash.each do |key, msg| %>
			<div class="alert-message <%= key %>"><p><%= msg %></p></div>
		<% end %>

		<%= form_for @defesa, :url => {:controller => "site", :action => "print_defesa_previa"} do |f| %>
		<fieldset>
			<legend>Dados do infrator</legend>

			<div class="clearfix">
				<%= f.label :nome %>
				<div class="input">
					<%= f.text_field :nome, :class => 'xlarge' %>
				</div>
			</div>

			<div class="clearfix">
				<label>O infrator é</label>
				<div class="input">
					<ul class="inputs-list">
						<li><label><%= f.radio_button :proprietario_condutor, "Proprietário" %> <span>Proprietário do veículo</span></label></li>
						<li><label><%= f.radio_button :proprietario_condutor, "Condutor" %> <span>Condutor do veículo</span></label></li>
					</ul>		
				</div>
			</div>

			<div class="clearfix">
				<%= f.label :residente %>
				<div class="input">
					<%= f.text_field :residente, :class => 'xlarge' %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :bairro %>
				<div class="input">
					<%= f.text_field :bairro %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :cidade %>
				<div class="input">
					<%= f.text_field :cidade %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :uf %>
				<div class="input">
					<%= f.text_field :uf %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :cep %>
				<div class="input">
					<%= f.text_field :cep, :placeholder => '74.000-000', :class => 'cep' %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :fone %>
				<div class="input">
					<%= f.text_field :fone, :placeholder => '62 0000-0000' %>
				</div>
			</div>	<div class="clearfix">
				<%= f.label :identidade %>
				<div class="input">
					<%= f.text_field :identidade %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :cpf %>
				<div class="input">
					<%= f.text_field :cpf %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :cnh %>
				<div class="input">
					<%= f.text_field :cnh %>
				</div>
			</div>	<div class="clearfix">
				<%= f.label :uf_cnh %>
				<div class="input">
					<%= f.text_field :uf_cnh %>
				</div>
			</div>

		</fieldset>

		<fieldset>
			<legend>Dados do veículo</legend>

			<div class="clearfix">
				<%= f.label :placa %>
				<div class="input">
					<%= f.text_field :placa, :placeholder => 'ABC-1234' %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :cor %>
				<div class="input">
					<%= f.text_field :cor %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :marca_modelo %>
				<div class="input">
					<%= f.text_field :marca_modelo %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :ano %>
				<div class="input">
					<%= f.text_field :ano, :placeholder => '2011/2012' %>
				</div>
			</div>

		</fieldset>

		<fieldset>
			<legend>Dados da possível infração</legend>

			<div class="clearfix">
				<%= f.label :numero_auto %>
				<div class="input">
					<%= f.text_field :numero_auto %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :data_auto %>
				<div class="input">
					<%= f.text_field :data_auto, :placeholder => '23/10/2011' %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :horario_auto %>
				<div class="input">
					<%= f.text_field :horario_auto, :placeholder => '14:25' %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :artigo_auto %>
				<div class="input">
					<%= f.text_field :artigo_auto %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :rodovia_auto %>
				<div class="input">
					<%= f.text_field :rodovia_auto %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :km_auto %>
				<div class="input">
					<%= f.text_field :km_auto %>
				</div>
			</div>
			<div class="clearfix">
				<%= f.label :municipio_auto %>
				<div class="input">
					<%= f.text_field :municipio_auto %>
				</div>
			</div>

		</fieldset>
		
		<fieldset>
			<legend>Razões para o cancelamento da possível infração</legend>

			<div class="clearfix">
				<%= f.label :razoes %>
				<div class="input">
					<%= f.text_area :razoes, :cols => 100, :rows => 6, :class => 'xxlarge' %>
				</div>
			</div>

		</fieldset>
		
		<div class="actions">
			<%= f.submit 'Gerar documento', :class => 'btn primary' %>
		</div>
		<% end %>
	</div>
</div>

app/views/site/index.html.erb
<div class="grid_12">
<div id="wrapper">
    <div class="slider-wrapper theme-default">
        <div class="ribbon"></div>
        <div id="slider" class="nivoSlider">
            <img src="/assets/nivo/fachada.png" width="940" alt="" />
            <a href="http://dev7studios.com"><img src="/assets/nivo/fachada.png" alt="" title="Com caption" /></a>
            <img src="/assets/nivo/fachada.png" alt="" />
            <img src="/assets/nivo/fachada.png" alt="" title="#htmlcaption" />
        </div>
        <div id="htmlcaption" class="nivo-html-caption">
            Com <a href="#"> link</a>.
        </div>
    </div>
</div>
<br/>

<p>
	<h1>Últimas notícias</h1>
	<table class="posts">
		<% @posts.each do |post| %>
			<tr>
				<td><%= data_formatada(post.created_at) %></td>
				<td><%= link_to post.title, post %></td>
			</tr>
		<% end %>
	</table>
	<%= link_to 'Mais notícias', posts_path %>
</p>

</div>

app/views/site/print_defesa_previa.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<%= wicked_pdf_stylesheet_link_tag "pdf.css" -%>

	<title>print_defesa_previa</title>
	
</head>

<body>
	<%#= wicked_pdf_image_tag image_path("logo_agetop.png") %>
	
	<div class="inner">
	
	<table class="table">
		<tr>
			<td><%= wicked_pdf_image_tag(image_path("logo_agetop.png"), :width => 150) %></td>
			<td class="center">
				<%= wicked_pdf_image_tag(image_path("logo_estado.png"), :width => 75) %><br/>
				SECRETARIA DE INFRA-ESTRUTURA<br/>
				AGÊNCIA GOIANA DE TRANSPORTES E OBRAS - AGETOP<br/>
				COMISSÃO DE DEFESA PRÉVIA - CODEP<br/>
				Rua 17 nº 188 Casa-04 Setor Aeroviário - Fone: (62) 3201-4772/3201-4773 - CEP: 74435-250 - Goiânia - Goiás<br/>
			</td>
		</tr>
	</table>
	
	<p class="center">
		<strong>DEFESA PRÉVIA</strong>
	</p>
	
	<p class="justify">
		Ilmo. Sr.<br/>
		Presidente da AGETOP - Comissão de Defesa Prévia - CODEP<br/>
		NESTA<br/><br/>
		Nome: <u><%= @defesa.nome %></u>. <u><%= @defesa.proprietario_condutor %></u> do veículo de PLACA: <u><%= @defesa.placa %></u>, COR: <u><%= @defesa.cor %></u>, 
		MARCA/MODELO: <u><%= @defesa.marca_modelo %></u>, ANO: <u><%= @defesa.ano %></u>.
	</p>
	
	<p class="justify">
		<strong>DADOS DA POSSÍVEL INFRAÇÃO:</strong><br/><br/>
		Auto de infração nº: <u><%= @defesa.numero_auto %></u>, data: <u><%= @defesa.data_auto %></u>, artigo: <u><%= @defesa.artigo_auto %></u>,
		rodovia: <u><%= @defesa.rodovia_auto %></u>, KM: <u><%= @defesa.km_auto %></u>, horário: <u><%= @defesa.horario_auto %></u>, município: <u><%= @defesa.municipio_auto %></u>,
		residente: <u><%= @defesa.residente %></u>, bairro: <u><%= @defesa.bairro %></u>, cidade: <u><%= @defesa.cidade %></u>, CEP: <u><%= @defesa.cep %></u>, fone: <u><%= @defesa.fone %></u>,
		C.I.: <u><%= @defesa.identidade %></u>, UF: <u><%= @defesa.uf %></u>, CNH: <u><%= @defesa.cnh %></u>, UF: <u><%= @defesa.uf_cnh %></u>, CPF: <u><%= @defesa.cpf %></u>,
		vem respeitosamente à presença de Vossa Senhoria, em prazo hábil, apresentar sua <strong>DEFESA PRÉVIA</strong> e solicitar o reestudo
		da NOTIFICAÇÃO DE AUTUAÇÃO em anexo, requerendo o seu <strong>cancelamento</strong> pelas razões a seguir: 
		<em class="mao"><%= @defesa.razoes %></em>
	</p>
	
	<p class="center">
		Nestes termos,<br/>
		Pede e espera provimento.<br/>
		Goiânia - GO, <%= data_formatada(Time.now) %>.<br/><br/>
		<u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</u><br/>
		Assinatura do requerente
	</p>
	
	<div class="border small">
	<div class="inner">
	<p>
		<u>Anexar documentos (Fotocópias) de:</u>
		<ul>
			<li>C.I.(Carteira de Identidade) e CPF (Cadastro de Pessoa Física),</li>
			<li>Pessoa Jurídica: Contrato social ou estatuto e CNPJ,</li>
			<li>CRLV (Certificado de Registro e Licenciatura de Veículo),</li>
			<li>Notificação de Autuação</li>
			<li>CNH (Carteira Nacional de Habilitação)</li>
			<li>Comprovante de endereço (água, luz, telefone ou fatura de cartão).</li>
		</ul>
			OBS.: A não apresentação de quaisquer documentos solicitados neste requerimento implicará no indeferimento sumário da presente Defesa Prévia.
	</p>
	</div>
	</div>
	
	</div>
	
</body>
</html>

app/views/site/print_recurso.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<%= wicked_pdf_stylesheet_link_tag "pdf.css" -%>

	<title>print_defesa_previa</title>
	
</head>

<body>
	<%#= wicked_pdf_image_tag image_path("logo_agetop.png") %>
	
	<div class="inner">
	
	<table class="table">
		<tr>
			<td><%= wicked_pdf_image_tag(image_path("logo_agetop.png"), :width => 150) %></td>
			<td class="center">
				<%= wicked_pdf_image_tag(image_path("logo_estado.png"), :width => 75) %><br/>
				SECRETARIA DE INFRA-ESTRUTURA<br/>
				AGÊNCIA GOIANA DE TRANSPORTES E OBRAS - AGETOP<br/>
				JUNTA ADMINISTRATIVA DE RECURSOS DE INFRAÇÕES - JARI<br/>
				Rua 17 nº 188 Casa-04 Setor Aeroviário - Fone: (62) 3201-4772/3201-4773 - CEP: 74435-250 - Goiânia - Goiás<br/>
			</td>
		</tr>
	</table>
	
	<p class="center">
		<strong>RECURSO DE INFRAÇÃO</strong>
	</p>
	
	<p class="justify">
		Ilmo. Sr.<br/>
		Presidente da JARI - AGETOP<br/>
		Junta Administrativa de Recursos de Infrações</br>
		NESTA<br/><br/>
		Eu: <u><%= @recurso.nome %></u>. <u><%= @recurso.proprietario_condutor %></u> do veículo de PLACA: <u><%= @recurso.placa %></u>, COR: <u><%= @recurso.cor %></u>, 
		MARCA/MODELO: <u><%= @recurso.marca_modelo %></u>, ANO: <u><%= @recurso.ano %></u>, CHASSI/RENAVAM: <u><%= @recurso.chassi_renavam %></u>.
	</p>
	
	<p class="justify">
		<strong>DADOS DA INFRAÇÃO:</strong><br/><br/>
		Auto de infração nº: <u><%= @recurso.numero_auto %></u>, data: <u><%= @recurso.data_auto %></u>, artigo: <u><%= @recurso.artigo_auto %></u>,
		rodovia: <u><%= @recurso.rodovia_auto %></u>, KM: <u><%= @recurso.km_auto %></u>, horário: <u><%= @recurso.horario_auto %></u>, município: <u><%= @recurso.municipio_auto %></u>,
		residente: <u><%= @recurso.residente %></u>, bairro: <u><%= @recurso.bairro %></u>, cidade: <u><%= @recurso.cidade %></u>, CEP: <u><%= @recurso.cep %></u>, fone: <u><%= @recurso.fone %></u>,
		C.I.: <u><%= @recurso.identidade %></u>, UF: <u><%= @recurso.uf %></u>, CNH: <u><%= @recurso.cnh %></u>, UF: <u><%= @recurso.uf_cnh %></u>, CPF: <u><%= @recurso.cpf %></u>, trabalhando na empresa: <u><%= @recurso.empresa %></u>.
	</p>
	<p>
		Vem respeitosamente à presença de Vossa Senhoria, em prazo hábil, interpor <strong>RECURSO</strong> solicitando o reestudo
		do Auto de Infração ou do Extrado de Multa em anexo, requerendo requerendo o seu 
		<strong><%= @recurso.cancelamento_restituicao %></strong>, banco: <u><%= @recurso.banco %></u>, agência: <u><%= @recurso.agencia %></u>, conta-corrente: <u><%= @recurso.conta_corrente %></u>, 
		para que seja feita a restituição do valor pago, caso este processo seja deferido, tendo em vista a inobservância da Legislação de Trânsito vigente,
		ou pelas razões a seguir: 
		<em class="mao"><%= @recurso.razoes %></em>
	</p>
	
	<p class="center">
		Nestes termos,<br/>
		Pede e espera provimento.<br/>
		Goiânia - GO, <%= data_formatada(Time.now) %>.<br/><br/>
		<u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</u><br/>
		Assinatura do requerente
	</p>
	
	<div class="border small">
	<div class="inner">
	<p>
		<u>Anexar documentos (Fotocópias) de:</u>
		<ul>
			<li>C.I.(Carteira de Identidade) e CPF (Cadastro de Pessoa Física);</li>
			<li>Pessoa Jurídica: Contrato social ou estatuto e CNPJ;</li>
			<li>CRLV (Certificado de Registro e Licenciatura de Veículo);</li>
			<li>Auto de Infração e/ou Notificação Detran;</li>
			<li>CNH (Carteira Nacional de Habilitação);</li>
			<li>Comprovante de endereço (água, luz, telefone ou fatura de cartão).</li>
		</ul>
			OBS.: A não apresentação de quaisquer documentos solicitados neste requerimento implicará no indeferimento sumário do presente Recurso.
	</p>
	</div>
	</div>
	
	</div>
	
</body>
</html>